### ISSUE TITLE
Is the extension working fine for relationships? 

### ISSUE THREAD

**Issue by igorsantos07** [keygenqt/yii2-parse#2]
I know from before that Parse relationships are troublesome when porting to ORM-like systems. I would like to know how is it working with this extension and what kinds of relationships we should configure to have the extension working fine. 

Thanks!

**Comment by keygenqt** [comment]
I do not quite understand your question. yii2-parse runs through curl 
and api.parse. I promptly inserted the ActiveRecord for themselves that 
would work prostinky project. Sam can not parse what can an ordinary 
base. The most essential part of running queries, and I checked. If 
something is not enough, you can show me or finish himself. I am glad to 
help. Refer if that.

19.08.15 14:49, Igor Santos пишет:

**Comment by igorsantos07** [comment]
Sorry, I could not understand every part of your message.
Anyway, Parse.com has a couple of different ways to store relationships.
Are hasOne, hasMany and manyMany relations working fine with this project's
ActiveRecord? Are the relationships serialized correctly to be stored and
retrieved in Parse?

I ask because I've seen other projects (in other languages though) having
trouble serializing the relationships.

**Comment by keygenqt** [comment]
hasOne, hasMany and manyMany - not sure if it works (most likely not). 
Check there is no time. For the serious project of the Council or take 
other or modify this, if something will be missed.

(hasOne, hasMany and manyMany - не уверен, что это работает (скорей 
всего нет). Проверить пока нет времени. Для серьезного проекта советую 
или взять другой или доработать этот, если чего-то будет не хватать.)

20.08.15 17:02, Igor Santos пишет:

> Sorry, I could not understand all parts of your message.
> Anyway, Parse.com has a couple of different ways to store relationships.
> Are hasOne, hasMany and manyMany relations working fine with this 
> project's
> ActiveRecord? Are the relationships serialized correctly to be stored and
> retrieved in Parse?
> 
> I ask because I've seen other projects (in other languages though) having
> trouble serializing the relationships.

**Comment by igorsantos07** [comment]
Too bad this is not a serious extension, but yet widely seen in the web. You should clearly state in the README it's an incomplete extension that you have no time to maintain.

**Comment by keygenqt** [comment]
Do or anyone that does not have to :). He wrote for myself, laid out for 
whom it is useful. I pointed out that this is a beta solution. If you 
will not have any function and append this vehicle.

(У ни кому ни чего не должен :). Писал для себя, выложил для того кому 
это пригодиться. Я указал что это бета решение. Если вам не хватит 
каких-то функция возмите и допишите.)

21.08.15 1:31, Igor Santos пишет:

**Comment by igorsantos07** [comment]
I think the readme is misleading, that's my point. Beta is something buggy, not something half-done :)
Knowing Parse support is bad around the web, I was wise to ask if the extension was complete, but others may just think Yii has Parse support when actually it does not have complete support.

**Comment by keygenqt** [comment]
Ok, i agree, I think would be added in the README that he has the full support of parse api.
